# https://hub.docker.com/_/influxdb
# Use root/example as user/password credentials
version: "3.1"

services:
  pubsub:
    # https://hub.docker.com/r/singularities/pubsub-emulator
    # https://stackoverflow.com/questions/69299480/running-google-pubsub-emulator-with-docker-compose-results-in-random-behavior
    image: singularities/pubsub-emulator
    depends_on:
      - postgres
    environment:
      PUBSUB_PROJECT_ID: fourkeys-pubsub
      PUBSUB_LISTEN_ADDRESS: 0.0.0.0:8432
    ports:
      - "8432:8432"

  event-handler:
    build:
      context: ./event-handler
    depends_on:
      - pubsub
    ports:
      - "8080:8080"
    environment:
      PUBSUB_EMULATOR_HOST: pubsub:8432
      PORT: 8080
      SECRET: apisecret
      PROJECT_NAME: fourkeys-pubsub

  github-parser:
    build:
      context: ./bq-workers/github-parser
    depends_on:
      - pubsub
    environment:
      PORT: 8082
      PUBSUB_EMULATOR_HOST: pubsub:8432
      SECRET: apisecret

  grafana:
    build:
      context: ./setup-postgres-docker/dashboard-postgres
    restart: always
    logging:
      driver: none
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    links:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dockerdb
    volumes:
      - ./setup-postgres-docker/postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init_1.sql
      - ./setup-postgres-docker/pgadmin/pgadmin-storage/dockerdb-fourkeys-2023-03-02_only_data.sql:/docker-entrypoint-initdb.d/docker_postgres_init_2.sql
  pgadmin:
    build:
      context: ./setup-postgres-docker/pgadmin/
      dockerfile: pgadmin-4.dockerfile
    restart: always
    logging:
      driver: none
    ports:
      - 15432:80
    depends_on:
      - postgres
    environment:
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DISABLE_POSTFIX: 1
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_SERVER_NAME: db
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/pgadmin-4-servers.json
      PGPASSFILE: /home/pgadmin/.pgpass
    volumes:
      - ./setup-postgres-docker/pgadmin/pgadmin-storage:/var/lib/pgadmin/storage/postgres_example.com:Z
      #- ./pgadmin-storage:/var/lib/pgadmin/storage/postgres_example.com/pgadmin-storage:Z
