{
 "title": "Four Keys",
 "time": { "from": "2022-08-01T03:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Lead Time for Changes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM lead_time_trend;" }
   ]
  },
  {
   "title": "Lead Time to Change Bucket",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM lead_time_bucket;"
    }
   ]
  },
  {
   "title": "Daily Deployments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM deployment_frequency_trend;"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM deployment_frequency_bucket"
    }
   ]
  },
  {
   "title": "Daily Median Time to Restore Services",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM time_to_restore_trend;"
    }
   ]
  },
  {
   "title": "Median Time to Restore Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM time_to_restore_bucket;"
    }
   ]
  },
  {
   "title": "Daily Change Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM change_failure_trend;"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM change_failure_bucket;"
    }
   ]
  }
 ]
}